// Central Supabase configuration used by the app.
const String supabaseUrl = 'https://qesmaldvlbfznrkrzdhc.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc21hbGR2bGJmem5ya3J6ZGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MjA3ODEsImV4cCI6MjA3OTI5Njc4MX0.bMDQmD99x7CdFTOfakCkHqQQsWcac5sc4awO6hMXfRQ';
