# Generated by Django 5.2.8 on 2025-11-15 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_distance_km', models.FloatField()),
                ('elevation_gain_m', models.FloatField()),
                ('path_coordinates', models.JSONField()),
                ('tags', models.JSONField()),
                ('ai_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('rest_type', models.TextField()),
                ('group_size', models.IntegerField()),
                ('start_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('difficulty', models.TextField()),
                ('personal_interest', models.JSONField()),
                ('template_name', models.CharField(default='Mẫu nhập nhanh', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('rest_type', models.TextField()),
                ('group_size', models.IntegerField()),
                ('start_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('difficulty', models.TextField()),
                ('personal_interest', models.JSONField()),
                ('personalized_equipment_list', models.JSONField(blank=True, null=True)),
                ('dangers', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.route')),
            ],
        ),
    ]
