# Generated by Django 5.2.8 on 2025-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_historyinput_personal_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.RemoveField(
            model_name='historyinput',
            name='personal_interest',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='personal_interest',
        ),
        migrations.AddField(
            model_name='historyinput',
            name='personal_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='dangers_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='personal_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dangers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='route',
            table='routes',
        ),
    ]
